### ISSUE TITLE
objc_msgSend Too many arguments to function call, expected 0, have 2

### ISSUE THREAD

**Issue by xinwo** [xmartlabs/XLRemoteImageView#13]
no problem with the demo project.
but when "pod install" into my project, error happens while compiling
I tried changing
enable strict checking of objc_msgSend calls
to No
nothing changes.

please help

**Comment by xinwo** [comment]
my mistake
changing
enable strict checking of objc_msgSend calls
to No
works

**Comment by Sajjon** [comment]
If anyone is experiencing problems with any Cocoapods project due to the objc_msgsend has too many arguments issue, I have fixed it using the post_installer script below.

What I am doing is that I am iterating through all targets in the Pods.xcproj and setting the flag 'ENABLE_STRICT_OBJC_MSGSEND' to NO.

```ruby
post_install do |installer|
	installer.project.targets.each do |target|
		target.build_configurations.each do |config|
			config.build_settings['ENABLE_STRICT_OBJC_MSGSEND'] = "NO"
		end
	end
end
```

**Comment by kunwarr** [comment]
@Sajjon Where did you write this script? In run scripts of pods project?

**Comment by Sajjon** [comment]
@iphonebytes
In the Podfile, the script will be run when you run "pod install"

(hence the command "post_install" :P )

**Comment by nithinreddy** [comment]
I did that in Build Settings of XLRemoteImageView in Pods, without having to edit Podfile and it worked.
